apiVersion: networking.k8s.io/v1

kind: Ingress

metadata:

  name: example-ingress
  labels: 
    app: nginx1

  annotations:

    nginx.ingress.kubernetes.io/rewrite-target: /$1

spec:

  rules:

    - host: k8.info

      http:

        paths:


          - path: /

            pathType: Prefix

            backend:

              service:

                name: newdep

                port:

                  number: 80

          - path: /s2

            pathType: Prefix

            backend:

              service:

                name: newdep1

                port:

                  number: 80

